#!/bin/bash
set -ex

cd $(dirname $0)/..

mkdir -p "./bin"

BIN_DIR="$(realpath ./bin)"

TMP_DIR=$(mktemp -d)

pushd "$TMP_DIR"

mkdir -p ./tar

IMAGE_REPO=${IMAGE_REPO:-rancher/rancher}
IMAGE_TAG=${IMAGE_TAG:-v2.8-head}
IMAGE=${IMAGE:-$IMAGE_REPO:$IMAGE_TAG}

docker pull $IMAGE

docker save $IMAGE > ./tar/rancher.tar

pushd tar

tar -xvf rancher.tar

for t in $(find . -type f -name "*.tar"); do
  if tar -tf "$t" "usr/bin/rancher"; then
    echo "Found /usr/bin/rancher in $t"
    tar -xvf "$t" usr/bin/rancher --strip-components 2
    mv rancher rancher-tmp
    break
  fi
done

popd

mkdir -p rancher

GIT_URL=${GIT_URL:-https://github.com/rancher/rancher.git}
GIT_BRANCH=${GIT_BRANCH:-release/v2.8}

git clone --depth 1 -b $GIT_BRANCH $GIT_URL ./rancher

ls -la rancher

export RANCHER_DIR=$TMP_DIR/rancher

mkdir -p "$RANCHER_DIR/bin"

mv ./tar/rancher-tmp "$RANCHER_DIR/bin/rancher"

rm -rf ./tar

popd
