#!/bin/bash
set -e

cd $(dirname $0)/..

METADATA_DIR=/var/lib/rancher-data/driver-metadata

mkdir -p $METADATA_DIR

cp ./data/data.json $METADATA_DIR/data.json

export SOME_K8S_VERSION=$(jq -r ".$DIST.releases[-1].version" < $METADATA_DIR/data.json)

source ./scripts/extract-rancher

cd $RANCHER_DIR

export CATTLE_RKE_METADATA_CONFIG='{"refresh-interval-minutes":"1440"}'

if [ -z "${V2PROV_TEST_DIST}" ]; then
  V2PROV_TEST_DIST=k3s
fi

./scripts/provisioning-tests
